title: Hønefoss dykkerklubb
description: Den offisielle hjemmesiden til Hønefoss dykkerklubb
theme: just-the-docs

url: "https://anderssh.github.io"
baseurl: "/hdk"

aux_links:
  GitHub repo: https://github.com/anderssh/hdk
logo: "{{ site.baseurl }}/assets/images/logo.png"


collections:
  pages:
    output: true
    permalink: /:path/